[package]
name = "test-haybale"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4"
haybale = { path = "../haybale", features = ["llvm-14", "vendor-boolector"] }
clap = { version = "4.0", features = ["derive"] }
llvm-ir = "0.8.2"
either = "1.8"
